/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tacebook.view;

import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tacebook.controller.ProfileController;
import tacebook.model.Comment;
import tacebook.model.Post;
import tacebook.model.Profile;

/**
 *
 * @author abel.iglesiasmoure
 */
public class GUIProfileView extends javax.swing.JDialog implements ProfileView {

    /**
     * Mantén a referencia ao obxecto controlador.
     */
    private final ProfileController profileController;

    /**
     * Indica o número de publicacións que se mostran na visualización.
     */
    private int postsShowed = 10;

    /**
     * Para formatear as datas.
     */
    private final SimpleDateFormat formatter;

    /**
     * Creates new form GUIProfileView
     *
     * @param parent
     * @param modal
     * @param profileController
     */
    public GUIProfileView(java.awt.Frame parent, boolean modal, ProfileController profileController) {
        super(parent, modal);
        this.profileController = profileController;
        this.formatter = new SimpleDateFormat("dd-MM-yyy 'ás' HH:mm:ss");
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jTablePosts.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                //Cargo os datos dos comentarios
                int row = jTablePosts.getSelectedRow();
                Post post = (Post) jTablePosts.getValueAt(row, 2);
                ArrayList<Comment> comments = post.getComments();

                DefaultTableModel myModel = (DefaultTableModel) jTableComments.getModel();
                myModel.setRowCount(0);

                for (int i = 0; i < comments.size() && !comments.isEmpty(); i++) {
                    Comment comment = comments.get(i);
                    myModel.addRow(new Object[]{
                        comment.getText(),
                        comment.getSourceProfile(),
                        comment.getDate()});
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUserProfile = new javax.swing.JLabel();
        jLabelTacebookLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStatusUser = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jButtonChangeStatus = new javax.swing.JButton();
        jButtonCloseSesion = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBiografia = new javax.swing.JPanel();
        jSplitBiografia = new javax.swing.JSplitPane();
        jPanelNorte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePosts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonNewPost = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelSur = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableComments = new javax.swing.JTable();
        jPanelAmigos = new javax.swing.JPanel();
        jSplitBiografia1 = new javax.swing.JSplitPane();
        jPanelNorte1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanelSur1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanelMensaxes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("tacebook - Perfil de usuario");

        jPanelHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/user.png"))); // NOI18N
        jLabel1.setText("Perfil do usuario: ");
        jPanel2.add(jLabel1);

        jLabelUserProfile.setText("jLabel2");
        jPanel2.add(jLabelUserProfile);

        jPanelHeader.add(jPanel2);

        jLabelTacebookLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/tacebook-logo.jpg"))); // NOI18N
        jPanelHeader.add(jLabelTacebookLogo);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/anatomy.png"))); // NOI18N
        jLabel3.setText("Estado actual: ");
        jPanel1.add(jLabel3);

        jLabelStatusUser.setText("jLabel4");
        jPanel1.add(jLabelStatusUser);

        jPanelHeader.add(jPanel1);

        getContentPane().add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jButtonChangeStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/anatomy.png"))); // NOI18N
        jButtonChangeStatus.setText("Cambiar estado");
        jPanelFooter.add(jButtonChangeStatus);

        jButtonCloseSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/exit.png"))); // NOI18N
        jButtonCloseSesion.setText("Pechar sesión");
        jPanelFooter.add(jButtonCloseSesion);

        getContentPane().add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.setToolTipText("");

        jPanelBiografia.setLayout(new java.awt.BorderLayout());

        jSplitBiografia.setDividerLocation(250);
        jSplitBiografia.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitBiografia.setToolTipText("");

        jPanelNorte.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("10 Últimas publicacións:");
        jPanelNorte.add(jLabel2, java.awt.BorderLayout.NORTH);

        jScrollPane1.setFocusTraversalPolicyProvider(true);

        jTablePosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Autor", "Texto", "Me gustas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePosts);

        jPanelNorte.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButtonNewPost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/post-it.png"))); // NOI18N
        jButtonNewPost.setText("Nova publicación");
        jButtonNewPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPostActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNewPost);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/speech-bubbles.png"))); // NOI18N
        jButton2.setText("Comentar");
        jPanel3.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/facebook-hand.png"))); // NOI18N
        jButton3.setText("Gústame");
        jPanel3.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/icon-plus.png"))); // NOI18N
        jButton4.setText("Ver anteriores publicacións");
        jPanel3.add(jButton4);

        jPanelNorte.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jSplitBiografia.setTopComponent(jPanelNorte);

        jPanelSur.setAutoscrolls(true);
        jPanelSur.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Comentarios:");
        jPanelSur.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jTableComments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Texto", "De", "Data"
            }
        ));
        jScrollPane2.setViewportView(jTableComments);

        jPanelSur.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jSplitBiografia.setRightComponent(jPanelSur);

        jPanelBiografia.add(jSplitBiografia, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Biografía", new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/post-it.png")), jPanelBiografia, ""); // NOI18N

        jPanelAmigos.setLayout(new java.awt.BorderLayout());

        jSplitBiografia1.setDividerLocation(250);
        jSplitBiografia1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitBiografia1.setToolTipText("");

        jPanelNorte1.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Lista de amig@s:");
        jPanelNorte1.add(jLabel5, java.awt.BorderLayout.NORTH);

        jScrollPane3.setFocusTraversalPolicyProvider(true);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Estado"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanelNorte1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/post-it.png"))); // NOI18N
        jButton7.setText("Ver biografía");
        jPanel4.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/letter.png"))); // NOI18N
        jButton8.setText("Enviar mensaxe privada");
        jPanel4.add(jButton8);

        jPanelNorte1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jSplitBiografia1.setTopComponent(jPanelNorte1);

        jPanelSur1.setAutoscrolls(true);
        jPanelSur1.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Tes solicitudes de amizade dos seguintes perfís:");
        jPanelSur1.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Texto", "De", "Data"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanelSur1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/accept.png"))); // NOI18N
        jButton5.setText("Aceptar solicitude");
        jPanel5.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/reject.png"))); // NOI18N
        jButton6.setText("Rexeitar solicitude");
        jPanel5.add(jButton6);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/handshake.png"))); // NOI18N
        jButton9.setText("Nova solicitude de amizade");
        jPanel5.add(jButton9);

        jPanelSur1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jSplitBiografia1.setRightComponent(jPanelSur1);

        jPanelAmigos.add(jSplitBiografia1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Amig@s", new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/people.png")), jPanelAmigos, ""); // NOI18N

        jPanelMensaxes.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Mensaxes privadas:");
        jPanelMensaxes.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lida", "Data", "De", "Texto"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanelMensaxes.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/email.png"))); // NOI18N
        jButton10.setText("Ler mensaxe");
        jPanel6.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/reject.png"))); // NOI18N
        jButton11.setText("Eliminar mensaxe");
        jPanel6.add(jButton11);

        jPanelMensaxes.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Mensaxes privadas", new javax.swing.ImageIcon(getClass().getResource("/tacebook/view/chat.png")), jPanelMensaxes, ""); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Biografía");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPostActionPerformed
        GregorianCalendar calendar = new GregorianCalendar();
        Date date = calendar.getTime();
        String text = "";
        Post post = new Post(0, date , text, profileController.getSessionProfile() , profileController.getSessionProfile());
    }//GEN-LAST:event_jButtonNewPostActionPerformed

    @Override
    public int getPostsShowed() {
        return postsShowed;
    }

    @Override
    public void showProfileMenu(Profile profile) {
        //Cambiar contenido de la cabecera
        jLabelUserProfile.setText(profile.getName());
        jLabelStatusUser.setText(profile.getStatus());

        //Actualizar tabla de posts
        ArrayList<Post> posts = profile.getPosts();
        DefaultTableModel myModel = (DefaultTableModel) jTablePosts.getModel();
        myModel.setRowCount(0);

        for (int i = 0; i < posts.size() && !posts.isEmpty(); i++) {
            Post post = posts.get(i);
            myModel.addRow(new Object[]{
                post.getDate(),
                post.getAuthor(),
                post,
                post.getProfileLikes().size()});
        }

        //Fago a tabla visible
        setVisible(true);

    }

    @Override
    public void showProfileNotFoundMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showCannotLikeOwnPostMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showAlreadyLikedPostMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showIsAlreadyFriendMessage(String profileName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showExistsFrienshipRequestMessage(String profileName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showDuplicateFrienshipRequestMessage(String profileName) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showConnectionErrorMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showReadErrorMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showWriteErrorMessage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void showNotFriendshipYourself() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonChangeStatus;
    private javax.swing.JButton jButtonCloseSesion;
    private javax.swing.JButton jButtonNewPost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelStatusUser;
    private javax.swing.JLabel jLabelTacebookLogo;
    private javax.swing.JLabel jLabelUserProfile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAmigos;
    private javax.swing.JPanel jPanelBiografia;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMensaxes;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JPanel jPanelNorte1;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JPanel jPanelSur1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitBiografia;
    private javax.swing.JSplitPane jSplitBiografia1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTableComments;
    private javax.swing.JTable jTablePosts;
    // End of variables declaration//GEN-END:variables
}
